import { test,expect } from '@playwright/test';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { stubNetwork } from './helpers.js';
test('full local sample: bounded DOM, responsive worker, byte-identical build',async({page},testInfo)=>{
 test.skip(!existsSync('Speedcam_Data_FEU.bin'),'Local proprietary sample absent');test.setTimeout(120000);
 await stubNetwork(page);await page.goto('/mivue-trafficcam/');
 await page.evaluate(()=>{window.frames=0;const frame=()=>{window.frames++;requestAnimationFrame(frame);};requestAnimationFrame(frame);});
 const started=Date.now();await page.getByLabel('Open file',{exact:true}).setInputFiles('Speedcam_Data_FEU.bin');
 await expect(page.getByTestId('record-count')).toHaveText('52935',{timeout:30000});const loadMs=Date.now()-started;
 await expect(page.getByTestId('record-row')).toHaveCount(100);expect(await page.locator('.leaflet-marker-icon').count()).toBe(0);
 await page.getByRole('button',{name:'Fit all records',exact:true}).click();
 const frames=await page.evaluate(()=>window.frames);expect(frames).toBeGreaterThan(1);
 await page.getByTestId('record-row').first().getByRole('button').focus();await page.keyboard.press('Enter');
 const editStart=Date.now();await page.locator('#details summary').click();await page.getByLabel('Four raw bytes (0–255)',{exact:true}).fill('1, 2, 3, 4');
 await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.locator('#changes')).toHaveText('1');await expect(page.getByTestId('save-status')).toHaveText('Saved locally');const editMs=Date.now()-editStart;
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();
 const projectEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();const projectBytes=await readFile(await (await projectEvent).path());
 await page.getByLabel('Open file',{exact:true}).setInputFiles({name:'sample-project.json',mimeType:'application/json',buffer:projectBytes});
 await expect(page.locator('#filename')).toHaveText('Speedcam_Data_FEU.bin');await expect(page.getByTestId('save-status')).toHaveText('Saved locally');
 await page.getByRole('button',{name:'Export',exact:true}).click();const before=await page.evaluate(()=>window.frames),buildStart=Date.now();
 await page.getByRole('button',{name:'Prepare binary',exact:true}).click();await expect(page.getByRole('button',{name:'Download validated binary',exact:true})).toBeEnabled({timeout:30000});const buildMs=Date.now()-buildStart;
 expect(await page.evaluate(()=>window.frames)).toBeGreaterThan(before);
 const event=page.waitForEvent('download');await page.getByRole('button',{name:'Download validated binary',exact:true}).click();
 expect(await readFile(await (await event).path())).toEqual(await readFile('Speedcam_Data_FEU.bin'));
 await page.getByRole('button',{name:'Close',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'List',exact:true}).click();await expect(page.getByTestId('record-row')).toHaveCount(100);
 await testInfo.attach('timings',{body:JSON.stringify({loadMs,editMs,buildMs,frames}),contentType:'application/json'});
 console.log(`Sample measurements: load ${loadMs} ms; edit ${editMs} ms; build ${buildMs} ms; ${frames} animation frames during load.`);
});
