import { test,expect } from '@playwright/test';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { stubNetwork } from './helpers.js';
test('full local sample: bounded DOM, responsive worker, byte-identical build',async({page},testInfo)=>{
 test.skip(!existsSync('Speedcam_Data_FEU.bin'),'Local proprietary sample absent');test.setTimeout(120000);
 await stubNetwork(page);await page.goto('/mivue-trafficcam/');
 await page.evaluate(()=>{window.frames=0;const frame=()=>{window.frames++;requestAnimationFrame(frame);};requestAnimationFrame(frame);});
 const started=Date.now();await page.getByLabel('Open file',{exact:true}).setInputFiles('Speedcam_Data_FEU.bin');
 await expect(page.getByTestId('record-count')).toHaveText('52935',{timeout:30000});const loadMs=Date.now()-started;
 await expect(page.getByTestId('record-row')).toHaveCount(100);expect(await page.locator('.leaflet-marker-icon').count()).toBe(0);
 await page.getByRole('button',{name:'Fit all records',exact:true}).click();
 await page.getByLabel('Show speed limits',{exact:true}).check();await page.getByLabel('Show metadata',{exact:true}).check();
 expect(Number(await page.locator('canvas.points').getAttribute('data-label-count'))).toBeLessThanOrEqual(200);
 const frames=await page.evaluate(()=>window.frames);expect(frames).toBeGreaterThan(1);
 await page.getByTestId('record-row').first().getByRole('button').focus();await page.keyboard.press('Enter');
 const editStart=Date.now();await page.locator('#details summary').click();await page.getByLabel('Four raw bytes (0–255)',{exact:true}).fill('1, 2, 3, 4');
 await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.locator('#changes')).toHaveText('1');await expect(page.getByTestId('save-status')).toHaveText('Saved locally');const editMs=Date.now()-editStart;
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();
 const projectEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();const projectBytes=await readFile(await (await projectEvent).path());
 await page.getByLabel('Open file',{exact:true}).setInputFiles({name:'sample-project.json',mimeType:'application/json',buffer:projectBytes});
 await expect(page.locator('#filename')).toHaveText('Speedcam_Data_FEU.bin');await expect(page.getByTestId('save-status')).toHaveText('Saved locally');
 await page.getByRole('button',{name:'Export',exact:true}).click();const before=await page.evaluate(()=>window.frames),buildStart=Date.now();
 await page.getByRole('button',{name:'Prepare binary',exact:true}).click();await expect(page.getByRole('button',{name:'Download validated binary',exact:true})).toBeEnabled({timeout:30000});const buildMs=Date.now()-buildStart;
 expect(await page.evaluate(()=>window.frames)).toBeGreaterThan(before);
 const event=page.waitForEvent('download');await page.getByRole('button',{name:'Download validated binary',exact:true}).click();
 expect(await readFile(await (await event).path())).toEqual(await readFile('Speedcam_Data_FEU.bin'));
 await page.getByRole('button',{name:'Close',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'List',exact:true}).click();await expect(page.getByTestId('record-row')).toHaveCount(100);
 await testInfo.attach('timings',{body:JSON.stringify({loadMs,editMs,buildMs,frames}),contentType:'application/json'});
 console.log(`Sample measurements: load ${loadMs} ms; edit ${editMs} ms; build ${buildMs} ms; ${frames} animation frames during load.`);
});
test('real country boundaries classify the local sample with bounded preview and cancellation',async({page})=>{
 test.skip(!existsSync('Speedcam_Data_FEU.bin'),'Local proprietary sample absent');test.setTimeout(120000);
 await stubNetwork(page);await page.goto('/mivue-trafficcam/');await page.getByLabel('Open file',{exact:true}).setInputFiles('Speedcam_Data_FEU.bin');await expect(page.getByTestId('record-count')).toHaveText('52935',{timeout:30000});
 await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByLabel('Export scope',{exact:true}).selectOption('countries');
 const countries=page.getByLabel('Countries',{exact:true});await expect(countries.locator('option')).toHaveCount(258,{timeout:30000});
 const poland=await countries.locator('option').filter({hasText:'Poland (PL)'}).getAttribute('value');await countries.selectOption(poland);
 await page.getByRole('button',{name:'Preview selection',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('button',{name:'Download selection report / notices',exact:true})).toBeDisabled();
 const started=Date.now();await page.getByRole('button',{name:'Preview selection',exact:true}).click();await expect(page.getByTestId('country-preview')).toContainText('Included:',{timeout:60000});
 await page.getByLabel('Preview group',{exact:true}).selectOption('kept');const rows=await page.getByTestId('country-preview-row').count();expect(rows).toBeLessThanOrEqual(100);expect(rows).toBeGreaterThan(0);
 console.log(`Real country preview: ${Date.now()-started} ms; ${rows} DOM rows.`);
 await page.getByRole('button',{name:'GeoJSON',exact:true}).click();await expect(page.getByTestId('export-error')).toBeVisible();
});
